In [1]:
import pandas as pd
import requests as r

In [9]:
import requests

url = "https://currency-exchange.p.rapidapi.com/listquotes"

headers = {
	"X-RapidAPI-Key": "8b2f553916msha856021a03cb2c0p1e0488jsnc95667dc63ba",
	"X-RapidAPI-Host": "currency-exchange.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

response.json()
df = pd.DataFrame(response.json())
df

      0
0   SGD
1   MYR
2   EUR
3   USD
4   AUD
5   JPY
6   CNH
7   HKD
8   CAD
9   INR
10  DKK
11  GBP
12  RUB
13  NZD
14  MXN
15  IDR
16  TWD
17  THB
18  VND